config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get 'home/presence'

  get 'home/presence_auth'

  post 'home/presence_auth'

  post 'home/presence_chat'

  resources :chats

  resources :users

  root 'chats#index'

end

app/models/chat.rb
class Chat < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :user_id, :message
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  require 'pusher'
  before_action :set_chat, only: [:show, :edit, :update, :destroy]

  # GET /chats
  # GET /chats.json
  def index
    @chats = Chat.all
  end

  # GET /chats/1
  # GET /chats/1.json
  def show
  end

  # GET /chats/new
  def new
    @chat = Chat.new
  end

  # GET /chats/1/edit
  def edit
  end

  # POST /chats
  # POST /chats.json
  def create
    @chat = Chat.new(chat_params)
    if @chat.save
      Pusher['test_channel'].trigger('my_event', {
        id: @chat.id,
        message: @chat.message,
        user: @chat.user.name,
        color: @chat.user.color,
        created_at: @chat.user.created_at.strftime("%I:%M%p")
      })
    end

    render nothing: true
  end

  # PATCH/PUT /chats/1
  # PATCH/PUT /chats/1.json
  def update
    respond_to do |format|
      if @chat.update(chat_params)
        format.html { redirect_to @chat, notice: 'Chat was successfully updated.' }
        format.json { render :show, status: :ok, location: @chat }
      else
        format.html { render :edit }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chats/1
  # DELETE /chats/1.json
  def destroy
    @chat.destroy
    respond_to do |format|
      format.html { redirect_to chats_url, notice: 'Chat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat
      @chat = Chat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chat_params
      params.require(:chat).permit(:user_id, :message)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	require 'pusher'
	layout 'home'

	protect_from_forgery :except => :presence_auth # stop rails CSRF protection for this action

	def index
	end

	def presence
	end

	def presence_auth

		# if using devise or some other login system, this is where you'd check
		# to see if the user is logged in
		# 
		# if current_user
		#   user_id = current_user.id
		#   user_name = current_user.name
		#   user_email = current_user.email
		#

		if params[:channel_name] and params[:socket_id] and !params[:channel_name].empty? and !params[:socket_id].empty?
			
			# Note: just simulating creating a random user

			user_id 			= rand(1000)
			user_name 			= "user-#{user_id}"
			user_email 			= "#{user_name}@andrew.com"
			hostname 			= Rails.application.config.app_properties[:hostname]

			response = Pusher[params[:channel_name]].authenticate(params[:socket_id], {
				:user_id => user_id, # => required
				:user_info => { # => optional - for example
					:name => user_name,
					:hostname => hostname,
					:email => user_email
				}
			})

			render :json => response
		else
			render :text => "forbidden", :status => '403'
	    end

	end

	def presence_chat
      @chat = Chat.new(presence_params)
      if @chat.save
		hostname 			= Rails.application.config.app_properties[:hostname]

        Pusher['presence-test_channel'].trigger('my_event', {
          id: @chat.id,
          message: @chat.message,
          hostname: hostname,
          user: @chat.user.name,
          color: @chat.user.color,
          created_at: @chat.user.created_at.strftime("%I:%M%p")
        })
      end
      render nothing: true
  	end

 	 private

	# Never trust parameters from the scary internet, only allow the white list through.
	def presence_params
		params.require(:chat).permit(:user_id, :message)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :color)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/._form.html.erb
<div id='chat-form'>
<% @chat = Chat.new %>
<%= form_for(@chat, remote: true) do |f| %>
  <div class="container">
      <div class="row">
          <div class="col-md-4 col-lg-3 col-sm-4 pull-right">
              <div class="panel panel-primary">
                  <div class="panel-heading" style='cursor: pointer'>
                      <span class="panel-max-min"><span class="glyphicon glyphicon-comment"></span> Chat [<span class='heading-user'></span>]</span>
                      <div class="btn-group pull-right">
                          <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                              <span class="glyphicon glyphicon-chevron-down"></span>
                          </button>
                          <ul class="dropdown-menu slidedown">
                              <% User.all.each do |u| %>
                                <li><a href="#" class='user-select' user='<%= u.id %>'><span class="glyphicon glyphicon-user">
                                </span> <%= u.name %></a></li>
                              <% end%>
                              <li class="divider"></li>
                              <li><a class='panel-max-min'><span class="glyphicon glyphicon-off"></span>
                                  Minimize/Maximize</a></li>
                          </ul>
                      </div>
                      <%= f.hidden_field :user_id %>
                  </div>
                  <div class="panel-body">
                      <div class="chat">
                        <div class="chat-body clearfix" style="height: 300px; overflow: scroll;">
                        </div>
                      </div>
                  </div>
                  <div class="panel-footer">
                      <div class="input-group">

                          <input id="btn-input" type="text" class="form-control input-sm" name="chat[message]" placeholder="Type your message here..." />
                          <span class="input-group-btn">
                              <input value=Send type=submit class="btn btn-warning btn-sm" id="btn-chat">

                          </span>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>

<% end %>
<div>

app/views/chats/_form.html.erb
<div id='chat-form'>
<% @chat = Chat.new %>
<%= form_for(@chat, remote: true) do |f| %>
  <div class="container">
      <div class="row">
          <div class="col-md-4 col-lg-3 col-sm-4 pull-right">
              <div class="panel panel-primary">
                  <div class="panel-heading" style='cursor: pointer'>
                      <span class="panel-max-min"><span class="glyphicon glyphicon-comment"></span> Chat [<span class='heading-user'></span>]</span>
                      <div class="btn-group pull-right">
                          <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                              <span class="glyphicon glyphicon-chevron-down"></span>
                          </button>
                          <ul class="dropdown-menu slidedown">
                              <% User.all.each do |u| %>
                                <li><a href="#" class='user-select' user='<%= u.id %>'><span class="glyphicon glyphicon-user">
                                </span> <%= u.name %></a></li>
                              <% end%>
                              <li class="divider"></li>
                              <li><a class='panel-max-min'><span class="glyphicon glyphicon-off"></span>
                                  Minimize/Maximize</a></li>
                          </ul>
                      </div>
                      <%= f.hidden_field :user_id %>
                  </div>
                  <div class="panel-body">
                      <div class="chat">
                        <div class="chat-body clearfix" style="height: 300px; overflow: scroll;">
                        </div>
                      </div>
                  </div>
                  <div class="panel-footer">
                      <div class="input-group">

                          <input id="btn-input" type="text" class="form-control input-sm" name="chat[message]" placeholder="Type your message here..." />
                          <span class="input-group-btn">
                              <input value=Send type=submit class="btn btn-warning btn-sm" id="btn-chat">

                          </span>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>

<% end %>
<div>

app/views/chats/_form.html.haml
#chat-form
  = form_for(Chat.new, remote: true) do |f|
    .container
      .row
        .col-md-4.col-lg-3.col-sm-4.pull-right
          .panel.panel-primary
            .panel-heading{style: 'cursor: pointer'}
              %span.panel-max-min
                %span.glyphicon.glyphicon-comment
                  Chat
                  %span.heading-user [select]

              .btn-group.pull-right
                %button.btn.btn-default.btn-xs.dropdown-toggle{type: 'button', 'data-toggle' => 'dropdown'}
                  %span.glyphicon.glyphicon-chevron-down
                %ul.dropdown-menu.slidedown
                  - User.all.each do |u|
                    %li
                      %a.user-select{href: "#", user: u.id}
                        %span.glyphicon.glyphicon-user
                        = u.name
                  %li.divider
                  %li
                    %a.panel-max-min
                      %span.glyphicon.glyphicon-off
                      Minimize/Maximize

              = f.hidden_field :user_id

            .panel-body
              .chat
                .chat-body.clearfix{ style: "height: 300px; overflow: scroll;"}

            .panel-footer
              .input-group
                %input.form-control.input-sm#btn-input{ type: "text", name: "chat[message]", placeholder: "Type your message here..."}
                %span.input-group-btn
                  %input.btn.btn-warning.btn-sm#btn-chat{value: 'Send', type: 'submit'}

app/views/chats/_form_presence.html.erb
<div id='chat-form'>
<% @chat = Chat.new %>
<%= form_for(@chat, remote: true, url: '/home/presence_chat') do |f| %>
  <div class="container">
      <div class="row">
          <div class="col-md-4 col-lg-3 col-sm-4 pull-right">
              <div class="panel panel-primary">
                  <div class="panel-heading" style='cursor: pointer'>
                      <span class="panel-max-min"><span class="glyphicon glyphicon-comment"></span> Chat Presence [<span class='heading-user'></span>]</span>
                      <div class="btn-group pull-right">
                          <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                              <span class="glyphicon glyphicon-chevron-down"></span>
                          </button>
                          <ul class="dropdown-menu slidedown">
                              <% User.all.each do |u| %>
                                <li><a href="#" class='user-select' user='<%= u.id %>'><span class="glyphicon glyphicon-user">
                                </span> <%= u.name %></a></li>
                              <% end%>
                              <li class="divider"></li>
                              <li><a class='panel-max-min'><span class="glyphicon glyphicon-off"></span>
                                  Minimize/Maximize</a></li>
                          </ul>
                      </div>
                      <%= f.hidden_field :user_id %>
                  </div>
                  <div class="panel-body">
                      <div class="chat">
                        <div class="chat-body clearfix" style="height: 300px; overflow: scroll;">
                        </div>
                      </div>
                  </div>
                  <div class="panel-footer">
                      <div class="input-group">

                          <input id="btn-input" type="text" class="form-control input-sm" name="chat[message]" placeholder="Type your message here..." />
                          <span class="input-group-btn">
                              <input value=Send type=submit class="btn btn-warning btn-sm" id="btn-chat">

                          </span>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>

<% end %>
<div>

app/views/chats/edit.html.erb
<h1>Editing Chat</h1>

<%= render 'form' %>

<%= link_to 'Show', @chat %> |
<%= link_to 'Back', chats_path %>

app/views/chats/index.html.erb
<br>

app/views/chats/new.html.erb
<h1>New Chat</h1>

<%= render 'form' %>

<%= link_to 'Back', chats_path %>

app/views/chats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @chat.user %>
</p>

<p>
  <strong>Message:</strong>
  <%= @chat.message %>
</p>

<%= link_to 'Edit', edit_chat_path(@chat) %> |
<%= link_to 'Back', chats_path %>

app/views/home/presence.html.erb
<div class="page-header">
  <h1>Presence Channel</h1>
</div>


<h2>Number of Users</h2>

<div class="member-count"></div>

<h2>Member List</h2>

<ul id="member-list" class="member-list">
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Chatty</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Chatty", "#", :class => "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="/chats">Chat</a></li>
          <li><a href="/users">Users</a></li>
          <!-- <li><a href="#contact">Contact</a></li> -->
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", :role => "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
  <%= render 'chats/form' %>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Chatty</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'pusher.min.js', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'chat-presence.js', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'shared/navigation' %>

  <div class="container">

    <%= render 'shared/navigation' %>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", :role => "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <p>Home Layout - Presence</p>

    <%= yield %>
  </div>

  <%= render 'chats/form_presence' %>

</body>
</html>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Chatty", "#", :class => "navbar-brand" %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/chats">Chat</a></li>
        <li><a href="/users">Users</a></li>
        <li><a href="/home/presence">Presence</a></li>
        <!-- <li><a href="#contact">Contact</a></li> -->
      </ul>
    </div>
  </div>
</nav>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.input :name %>
  <%= f.input :color, collection: [:red,:green,:yellow,:orange] %>
  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<%= render 'chats/form' %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>